/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index.route";
import { Route as DevlogIndexRouteImport } from "./routes/devlog/index.route";

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as unknown);

const DevlogIndexRouteRoute = DevlogIndexRouteImport.update({
	id: "/devlog/",
	path: "/devlog/",
	getParentRoute: () => rootRoute,
} as unknown);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRoute;
		};
		"/devlog/": {
			id: "/devlog/";
			path: "/devlog";
			fullPath: "/devlog";
			preLoaderRoute: typeof DevlogIndexRouteImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRouteRoute;
	"/devlog": typeof DevlogIndexRouteRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRouteRoute;
	"/devlog": typeof DevlogIndexRouteRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRouteRoute;
	"/devlog/": typeof DevlogIndexRouteRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/devlog";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/devlog";
	id: "__root__" | "/" | "/devlog/";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRouteRoute: typeof IndexRouteRoute;
	DevlogIndexRouteRoute: typeof DevlogIndexRouteRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRouteRoute: IndexRouteRoute,
	DevlogIndexRouteRoute: DevlogIndexRouteRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/devlog/"
      ]
    },
    "/": {
      "filePath": "index.route.tsx"
    },
    "/devlog/": {
      "filePath": "devlog/index.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
