name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

    - name: Install dependencies and build
      run: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install
        pnpm run build
    
    - name: Transfer build files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: dist/ # React 빌드 결과 폴더
        target: /var/www/html/temp_build/

    - name: Run update script on server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          zsh /scripts/blog/build_push.sh
