name: 서버 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: 환경 파일 만들기
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

    - name: 프로젝트 빌드
      run: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install
        pnpm run build
    
    - name: scp 전송
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: dist/ 
        target: /var/www/html/temp_build/

    - name: script 실행
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          zsh /scripts/blog/build_push.sh
